<?php

return [
    'Swoole\Command\ICommand' => APP_PATH . '/libs/Swoole/Command/ICommand.php',
    'Swoole\Command\BooleanAckCommand' => APP_PATH . '/libs/Swoole/Command/BooleanAckCommand.php',
    'Swoole\Command\CommandFactory' => APP_PATH . '/libs/Swoole/Command/CommandFactory.php',
    'Swoole\Command\CommandHeader' => APP_PATH . '/libs/Swoole/Command/CommandHeader.php',
    'Swoole\Command\RequestCommand' => APP_PATH . '/libs/Swoole/Command/RequestCommand.php',
    'Swoole\Command\ResponseCommand' => APP_PATH . '/libs/Swoole/Command/ResponseCommand.php',
    'Swoole\Command\ResponseStatus' => APP_PATH . '/libs/Swoole/Command/ResponseStatus.php',
    'Swoole\Core\CodecFactory' => APP_PATH . '/libs/Swoole/Core/CodecFactory.php',
    'Swoole\Core\Connection' => APP_PATH . '/libs/Swoole/Core/Connection.php',
    'Swoole\Core\Decoder' => APP_PATH . '/libs/Swoole/Core/Decoder.php',
    'Swoole\Core\Encoder' => APP_PATH . '/libs/Swoole/Core/Encoder.php',
    'Swoole\Core\implement\BaseConnection' => APP_PATH . '/libs/Swoole/Core/BaseConnection.php',
    'Swoole\Core\implement\ServerConnection' => APP_PATH . '/libs/Swoole/Core/ServerConnection.php',
    'Swoole\Protocol\Base' => APP_PATH . '/libs/Swoole/Protocol/Base.php',
    'Swoole\Protocol\IProtocol' => APP_PATH . '/libs/Swoole/Protocol/IProtocol.php',
    'Swoole\Service\Driver' => APP_PATH . '/libs/Swoole/Service/Driver.php',
    'Swoole\Service\implement\Server' => APP_PATH . '/libs/Swoole/Service/implement/Server.php',
    'Swoole\Service\implement\TcpServer' => APP_PATH . '/libs/Swoole/Service/implement/TcpServer.php',
    'Swoole\Util\Console' => APP_PATH . '/libs/Swoole/Util/Console.php',
    'Swoole\Util\MessagePacker' => APP_PATH . '/libs/Swoole/Util/MessagePacker.php',
    'Swoole\Util\ByteBuffer' => APP_PATH . '/libs/Swoole/Util/ByteBuffer.php',
    'Swoole\Util\Config' => APP_PATH . '/libs/Swoole/Util/Config.php',
    'Swoole\Util\Log' => APP_PATH . '/libs/Swoole/Util/Log.php',
    'Swoole\Queue\Queue' => APP_PATH . '/libs/Swoole/Queue/Queue.php',
    'Swoole\Queue\FileQueue' => APP_PATH . '/libs/Swoole/Queue/FileQueue.php',
    'Swoole\Queue\FileWorker' => APP_PATH . '/libs/Swoole/Queue/FileWorker.php',
    'Swoole\Queue\LogEntity' => APP_PATH . '/libs/Swoole/Queue/LogEntity.php',
    'Swoole\Queue\LogIndex' => APP_PATH . '/libs/Swoole/Queue/LogIndex.php',
    'Swoole\Queue\FileBufferException' => APP_PATH . '/libs/Swoole/Queue/FileBufferException.php',
    'Swoole\Queue\FileFormatException' => APP_PATH . '/libs/Swoole/Queue/FileFormatException.php',
    'Swoole\Queue\FileQueueException' => APP_PATH . '/libs/Swoole/Queue/FileQueueException.php',
];